#ifndef HYPHENATION_PATTERNS_H
#define HYPHENATION_PATTERNS_H

#include <cstddef>
#include <cstdint>

// Descriptor for a Typst hypher pre-compiled binary trie stored in flash.
// Generated by tools/generate_trie_header.py from .bin files downloaded from
// https://github.com/typst/hypher/tree/main/tries
struct HyphenationTrieData {
  std::size_t rootOffset;
  const std::uint8_t* data;
  std::size_t size;
};

#endif  // HYPHENATION_PATTERNS_H
